---
- name: "SSH USER {{ gazella_project|upper }} {{ gazella_environment|upper }} - Add Gazellacom system group security"
  become: yes
  ansible.builtin.group:
    name: "{{ gazella_local_group }}"
    state: present
  tags:
    - gazella_user

- name: "SSH USER {{ gazella_project|upper }} {{ gazella_environment|upper }} - Add Gazellacom AWX user"
  ansible.builtin.user:
    name: "{{ gazella_local_user }}"
    group: "{{ gazella_local_group }}"
    state: present
    shell: "{{ gazella_local_user_shell }}"
    password: "{{ gazella_local_user_passwd }}"
    update_password: "{{ gazella_local_user_update_password }}"
    system: "{{ gazella_local_user_system }}"
  tags:
    - gazella_user

- name: "SSH USER {{ gazella_project|upper }} {{ gazella_environment|upper }} - Add directory for /home/{{ gazella_local_user }}/.ssh User"
  file:
    path: "/home/{{ gazella_local_user }}/.ssh"
    state: directory
    mode: 0700
    owner: "{{ gazella_local_user }}"
    group: "{{ gazella_local_group }}"

- name: "SSH USER {{ gazella_project|upper }} {{ gazella_environment|upper }} - Copy the file from buffer key folder  {{ gazella_local_user }}"
  ansible.builtin.copy: 
    src: "key/{{ gazella_project|upper }}-{{ gazella_user_new|upper }}-USER.pub"
    dest: "/home/{{ gazella_local_user }}/.ssh/{{ gazella_project|upper }}-{{ gazella_user_new|upper }}-USER.pub"

- name: "SSH USER {{ gazella_project|upper }} {{ gazella_environment|upper }} - Add key for {{ gazella_local_user }} User"
  ansible.posix.authorized_key:
    user: "{{ gazella_local_user }}"
    state: present
    key: "{{ lookup('file', 'key/{{ gazella_project|upper }}-{{ gazella_user_new|upper }}-USER.pub') }}"

- name: "SSH USER {{ gazella_project|upper }} {{ gazella_environment|upper }} - Delete file {{ gazella_project|upper }}-{{ gazella_user_new|upper }}-USER.pub"
  ansible.builtin.file:
    path: "/home/{{ gazella_local_user }}/.ssh/{{ gazella_project|upper }}-{{ gazella_user_new|upper }}-USER.pub"
    state: absent
  ignore_errors: yes

- name: "Set Privilegis for COM APPLICATION"
  ansible.builtin.include_tasks: privileges_com.yml
  when: gazella_app == 'com'

- name: "Set Privilegis for ERP APPLICATION"
  ansible.builtin.include_tasks: privileges_erp.yml
  when: gazella_app == 'erp'

